# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTestfilter():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_testfilter(self):
    self.driver.get("https://www.saucedemo.com/")
    self.driver.set_window_size(1936, 1066)
    self.driver.find_element(By.ID, "user-name").click()
    self.driver.find_element(By.ID, "user-name").send_keys("standard_user")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("secret_sauce")
    self.driver.find_element(By.ID, "login-button").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]").click()
    dropdown = self.driver.find_element(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]")
    dropdown.find_element(By.XPATH, "//option[. = 'Name (Z to A)']").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "*[data-test=\"product_sort_container\"]")
    assert len(elements) > 0
  
